name: Building[main]

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  # Build the Hello World test application
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        love_version: ['11.4']

    steps:
    - uses: actions/checkout@v3

    - uses: nhartland/love-build@master
      id: love-build
      with:
        app_name: 'snake'
        love_version: ${{ matrix.love_version }}
        source_dir: './src'
    
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          ${{ steps.love-build.outputs.macos-filename }}
          ${{ steps.love-build.outputs.win32-filename }}
          ${{ steps.love-build.outputs.win64-filename }}
          ${{ steps.love-build.outputs.love-filename }}
